CREATE TABLE user (
	id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(191) NOT NULL,
    name VARCHAR(191) NOT NULL,
    password VARCHAR(191) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM product;
ALTER TABLE product MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;